require 'rails'
require 'active_support'
module Rockauth
  autoload :Authenticator,             'rockauth/authenticator'
  autoload :Client,                    'rockauth/client'
  autoload :Configuration,             'rockauth/configuration'
  autoload :ControllerConcern,         'rockauth/controller_concern'
  autoload :Engine,                    'rockauth/engine'
  autoload :Errors,                    'rockauth/errors'
  autoload :ProviderUserInformation,   'rockauth/provider_user_information'
  autoload :ProviderValidationConcern, 'rockauth/provider_validation_concern'
  autoload :ResourceOwnerConcern,      'rockauth/resource_owner_concern'
end
require 'rockauth/configuration'
require 'rockauth/engine'
